[package]
name = "bevy_experiments"
version = "0.1.0"
edition = "2024"

[dependencies]
noise = "0.9"
anyhow = "1.0.100"
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
bytemuck = "1.24.0"
rand = "0.9.2"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
